[package]
name = "prisma_cli"
version.workspace = true
edition.workspace = true

[dependencies.prisma-client-rust-cli]
git = "https://github.com/Brendonovich/prisma-client-rust"
tag = "0.6.8"
features = ["sqlite"]
