name: Deploy / Root

on:
  workflow_run:
    workflows:
      - Build
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        id: artifact-download
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build
          check_artifacts: true
          search_artifacts: true
          workflow: main.yaml
          if_no_artifact_found: fail

      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: dist/apps/root/deploy/
          command: pages publish --project-name=${{ secrets.CF_PROJECT_ROOT_NAME }} --skip-caching
